# Generated by Django 6.0 on 2026-02-10 20:11

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='departments_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='departments_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Departamento',
                'verbose_name_plural': 'Departamentos',
                'db_table': 'departamento',
            },
        ),
        migrations.CreateModel(
            name='Plaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='plazas_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='plazas_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plazas',
                'verbose_name_plural': 'Plazas',
                'db_table': 'plaza',
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('fecha_pago', models.DateField()),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='nominas', to='nomina.departamento')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='nominas_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='nominas_updated', to=settings.AUTH_USER_MODEL)),
                ('plaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='nominas', to='nomina.plaza')),
            ],
            options={
                'verbose_name': 'Nomina',
                'verbose_name_plural': 'Nominas',
                'db_table': 'nomina',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(blank=True, max_length=255, null=True)),
                ('nombre_completo', models.CharField(blank=True, max_length=255, null=True)),
                ('sd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sdi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('periodicidad_pago', models.IntegerField(blank=True, null=True)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='empleados', to='nomina.departamento')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employees_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='employees_updated', to=settings.AUTH_USER_MODEL)),
                ('plaza', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='empleados', to='nomina.plaza')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
            },
        ),
        migrations.CreateModel(
            name='Recibo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('sdi', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('periodicidad_pago', models.IntegerField(blank=True, null=True)),
                ('sueldos_salarios', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('isr_determinado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('isr_pagar', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subsidio_empleo_causado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('subsidio_empleo_entregado', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('imss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recibos', to='nomina.empleado')),
                ('nomina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recibos', to='nomina.nomina')),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recibos_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='recibos_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recibo',
                'verbose_name_plural': 'Recibos',
                'db_table': 'recibo',
            },
        ),
    ]
