# Generated by Django 6.0 on 2026-02-11 18:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='recibo',
            name='nomina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='recibos', to='nomina.nomina'),
        ),
        migrations.CreateModel(
            name='IsrQuincenal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_inferior', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('limite_superior', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cuota_fija', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('porcentaje_excedente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='isrs_quincenal_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='isrs_quincenal_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ISR quincenal',
                'verbose_name_plural': 'ISR quincenal',
                'db_table': 'isr_quincenal',
            },
        ),
        migrations.CreateModel(
            name='IsrSemanal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limite_inferior', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('limite_superior', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('cuota_fija', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('porcentaje_excedente', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='isrs_semanal_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='isrs_semanal_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'ISR semanal',
                'verbose_name_plural': 'ISR semanal',
                'db_table': 'isr_semanal',
            },
        ),
        migrations.CreateModel(
            name='Uma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('porcentaje_uma', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('factor_mensual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_created', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='umas_created', to=settings.AUTH_USER_MODEL)),
                ('user_updated', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='umas_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UMA',
                'verbose_name_plural': 'UMA',
                'db_table': 'uma',
            },
        ),
    ]
