# Generated by Django 6.0 on 2026-02-11 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0002_alter_recibo_nomina_isrquincenal_isrsemanal_uma'),
    ]

    operations = [
        migrations.AddField(
            model_name='isrquincenal',
            name='ejercicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='isrsemanal',
            name='ejercicio',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uma',
            name='ejercicio',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
