# Generated by Django 6.0 on 2026-02-11 22:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0003_isrquincenal_ejercicio_isrsemanal_ejercicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uma',
            name='limite_max',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
