# Generated by Django 6.0 on 2026-02-12 22:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nomina', '0004_uma_limite_max'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recibo',
            old_name='isr_pagar',
            new_name='isr_retenido',
        ),
    ]
