# Generated by Django 6.0 on 2026-01-05 22:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='acciongrupo',
            name='accion_grupo_accion_id_grupo_id_unique',
        ),
        migrations.AlterField(
            model_name='acciongrupo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='acciones_relacionadas', to='auth.group'),
        ),
        migrations.AddConstraint(
            model_name='acciongrupo',
            constraint=models.UniqueConstraint(fields=('accion', 'grupo'), name='accion_grupo_accion_grupo_unique'),
        ),
    ]
