# Generated by Django 6.0 on 2026-01-05 22:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_remove_acciongrupo_accion_grupo_accion_id_grupo_id_unique_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acciongrupo',
            name='accion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='grupos_relacionados', to='dashboard.accion'),
        ),
    ]
