# Generated by Django 6.0 on 2026-02-10 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('dashboard', '0003_alter_acciongrupo_accion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accion',
            name='seccion_menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='dashboard.seccionmenu'),
        ),
        migrations.AlterField(
            model_name='acciongrupo',
            name='accion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grupos_relacionados', to='dashboard.accion'),
        ),
        migrations.AlterField(
            model_name='acciongrupo',
            name='grupo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acciones_relacionadas', to='auth.group'),
        ),
        migrations.DeleteModel(
            name='Grupo',
        ),
    ]
